name: Android Release
on:
  push:
    branches:
      - main

jobs:
  update-version:
    name: Update Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        uses: actions/checkout@v2

      - name: Update Version Number
        run: echo "::set-output name=version::$(cat version.txt)"

  release:
    name: Release
    runs-on: ubuntu-latest

    needs: update-version

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.1' # Replace with your desired Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Set up Git
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name 'ItsAash'
          git config --global user.email 'aashishneupane125@example.com'

      - name: Create Version Number
        id: version_number
        run: |
          echo ${{ needs.update-version.outputs.version }} > version.txt

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: v${{ needs.update-version.outputs.version }}
          release_name: Release v${{ needs.update-version.outputs.version }}
          body: |
            Description of the release.
          draft: false
          prerelease: false

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Release APK
          path: path/to/android/app/build/app/outputs/flutter-apk/app-release.apk
